stages:
  - test
  - build
  - deploy

test-pre-commit:
  stage: test
  tags:
    - darp-group-shell-runner
  script:
    - source ~/miniconda3/bin/activate && pre-commit run --all-files

clean-pre-commit:
  stage: test
  tags:
    - darp-group-shell-runner
  script:
    - source ~/miniconda3/bin/activate && pre-commit clean
  when: manual

build:
  stage: build
  when: manual
  tags:
    - darp-group-shell-runner
  script:
    - source deploy/docker-version
    - docker compose build "$CI_PROJECT_NAME"

deploy-test:
  stage: deploy
  needs: ["build"]
  when: manual
  tags:
    - darp-group-shell-runner
  script:
    - deploy/push-and-run "$TEST_DOCKER_HOST"

deploy-prod:
  stage: deploy
  when: manual
  needs: ["build"]
  tags:
    - darp-group-shell-runner
  script:
    - deploy/push-and-run "$PRODUCTION_DOCKER_HOST"
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
