services:
  registry:
    build:
      context: .
    environment:
      - UVICORN_PORT
      - DATABASE_URL
      - OPENAI_API_KEY
      - OPENAI_API_BASE
      - LLM_PROXY
      - LLM_MODEL
    image: "$REGISTRY_IMAGE"
    container_name: "$CI_PROJECT_NAME"
    pull_policy: always
    restart: always
    volumes:
      - /var/lib/highkey/$CI_PROJECT_NAME/logs:/workspace/logs

networks:
  default:
    name: highkey_network
    external: true