services:
  registry:
    build:
      context: .
      dockerfile: registry/Dockerfile
    environment:
      - UVICORN_PORT
      - DATABASE_URL
      - OPENAI_API_KEY
      - OPENAI_API_BASE
      - LLM_PROXY
      - LLM_MODEL
    image: "$REGISTRY_IMAGE"
    container_name: registry
    pull_policy: always
    restart: always
    volumes:
      - /var/lib/hipasus/registry/api/logs:/workspace/logs

  registry_mcp_server:
    build:
      context: .
      dockerfile: mcp_server/Dockerfile
    environment:
      - LOG_LEVEL
      - REGISTRY_URL
      - OPENAI_API_KEY
      - OPENAI_API_BASE
      - LLM_PROXY
      - LLM_MODEL
    image: "$MCP_REGISTRY_IMAGE"
    container_name: registry_mcp_server
    pull_policy: always
    restart: always
    volumes:
      - /var/lib/hipasus/registry/mcp_server/logs:/workspace/logs

networks:
  default:
    name: highkey_network
    external: true